version: '3.8'

services:
  django_gunicorn:
    volumes:
      - static:/app/static
    build:
      context: .
    image: joelgxp/clinica-django:latest
    ports:
      - 8003:8000

  nginx:
    build: ./nginx
    image: joelgxp/clinica-nginx:latest
    volumes:
      - static:/static
    ports:
      - 9003:80
    depends_on:
      - django_gunicorn

volumes:
  static:
