# Generated by Django 5.0.1 on 2024-02-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='atendido',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='logradouro',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='registro',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='solicitacao',
            field=models.CharField(choices=[('PRIMEIRA_HABILITACAO', 'PRIMEIRA HABILITAÇÃO'), ('RENOVACAO', 'RENOVAÇÃO'), ('RENOVACAO_ATIV_REM', 'RENOVAÇÃO COM A.R.'), ('ADICAO_CATEGORIA', 'ADIÇÃO DE CATEGORIA'), ('MUDANCA_CATEGORIA', 'MUDANÇA DE CATEGORIA'), ('ALTERACAO_DADOS', 'ALTERAÇÃO DE DADOS')], max_length=45),
        ),
        migrations.CreateModel(
            name='FluxoDeCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'DINHEIRO')], max_length=45)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.paciente')),
            ],
        ),
    ]
