# Generated by Django 5.0.1 on 2024-02-02 00:15

import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientemodel',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='uf_cidade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='uf_emissor',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='uf_naturalidade',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='PacienteExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('visao_le', models.IntegerField()),
                ('visao_ld', models.IntegerField()),
                ('correcao_visual', models.CharField(max_length=10, verbose_name=(('sim', 'Sim'), ('nao', 'Não')))),
                ('campo_visual_le', models.IntegerField()),
                ('campo_visual_ld', models.IntegerField()),
                ('exame_validade', models.DateField()),
                ('conclusao', models.CharField(max_length=10, verbose_name=(('apto', 'Apto'), ('inapto', 'Inapto')))),
                ('complemento', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.pacientemodel')),
            ],
        ),
    ]
