# Generated by Django 5.0.1 on 2024-02-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_pacientemodel_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteexame',
            name='conclusao',
            field=models.CharField(choices=[('apto', 'Apto'), ('inapto', 'Inapto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pacienteexame',
            name='correcao_visual',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10),
        ),
    ]
