# Generated by Django 5.0.1 on 2024-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_paciente_atendido_alter_paciente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxodecaixa',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='fluxodecaixa',
            name='valor_dinheiro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxodecaixa',
            name='valor_pix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'DINHEIRO'), ('PIX/DINHEIRO', 'PIX/DINHEIRO')], max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='solicitacao',
            field=models.CharField(choices=[('PRIMEIRA_HABILITACAO', 'PRIMEIRA HABILITAÇÃO'), ('RENOVACAO', 'RENOVAÇÃO'), ('RENOVACAO_ATIV_REM', 'RENOVAÇÃO ATIV. REMUNERADA'), ('ADICAO_CATEGORIA', 'ADIÇÃO DE CATEGORIA'), ('MUDANCA_CATEGORIA', 'MUDANÇA DE CATEGORIA'), ('ALTERACAO_DADOS', 'ALTERAÇÃO DE DADOS')], max_length=45),
        ),
    ]
