# Generated by Django 5.0.1 on 2024-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_valor_fluxodecaixa_valor_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxodecaixa',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
