# Generated by Django 5.0.1 on 2024-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_fluxodecaixa_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='valor_total',
            field=models.FloatField(),
        ),
    ]
