# Generated by Django 5.0 on 2024-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_fluxodecaixa_valor_dinheiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='solicitacao',
        ),
        migrations.AddField(
            model_name='pacienteexame',
            name='solicitacao',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='RENOVACAO', max_length=45),
        ),
    ]
