# Generated by Django 5.0 on 2024-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_paciente_solicitacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atendido',
        ),
        migrations.AddField(
            model_name='pacienteexame',
            name='atendimento',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='pacienteexame',
            name='conclusao',
            field=models.CharField(choices=[('apto', 'APTO'), ('inapto', 'INAPTO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pacienteexame',
            name='correcao_visual',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pacienteexame',
            name='solicitacao',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], max_length=45),
        ),
    ]
