# Generated by Django 5.0 on 2024-02-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_paciente_atendido_pacienteexame_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxodecaixa',
            name='pacienteexame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.pacienteexame'),
        ),
        migrations.AlterField(
            model_name='pacienteexame',
            name='atendimento',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=10),
        ),
    ]
