# Generated by Django 5.0.1 on 2024-02-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_exame_solicitacao_atendimento_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='id_exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.exame'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='solicitacao',
            field=models.CharField(choices=[('PRIMEIRA_HABILITACAO', 'PRIMEIRA HABILITAÇÃO'), ('RENOVACAO', 'RENOVAÇÃO'), ('RENOVACAO_ATIV_REM', 'RENOVAÇÃO ATIV. REMUNERADA'), ('ADICAO_CATEGORIA', 'ADIÇÃO DE CATEGORIA'), ('MUDANCA_CATEGORIA', 'MUDANÇA DE CATEGORIA'), ('ALTERACAO_DADOS', 'ALTERAÇÃO DE DADOS')], max_length=45),
        ),
    ]
