# Generated by Django 5.0.1 on 2024-02-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_atendimento_id_exame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='id_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.paciente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='id_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.pagamento'),
        ),
    ]
