name: CI

on:
  push:
    branches:
      - main
      - clinica

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}   
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: | 
            joelgxp/clinica:${{github.run_number}}
            joelgxp/clinica:latest

      
        
          
